# Generated by Django 3.2.6 on 2022-02-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='cgpa',
            field=models.FloatField(default=3.0),
        ),
    ]
