# Generated by Django 3.2.6 on 2022-02-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentregistration_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='cgpa',
            field=models.FloatField(default=3.0, max_length=4),
        ),
    ]
